proyectoFinal/app_proyecto/urls.py
from django.urls import path
from .views import ConsultasListView, ConsultasDetailView, ConsultasCreateView, ConsultasDeleteView, ConsultasUpdateView
from .router import router

app_name = "consultas"

urlpatterns = [
    path('', ConsultasListView.as_view(), name = 'all'),
    path('<int:pk>/detail/', ConsultasDetailView.as_view(), name = 'detail'),
    path('create/', ConsultasCreateView.as_view(), name = 'create'),
    path('<int:pk>/update/', ConsultasUpdateView.as_view(), name = 'update'),
    path('<int:pk>/delete/', ConsultasDeleteView.as_view(), name = 'delete')
]

urlpatterns += router.urls

proyectoFinal/proyectoFinal/urls.py
from django.contrib import admin
from django.urls import path, include 

from .views import LandingPage, Contacto, Empresa, Portfolio, Index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPage.as_view(), name='landing_page'),
    path('contacto/', Contacto.as_view(), name='contacto_page'),
    path('empresa/', Empresa.as_view(), name='empresa_page'),
    path('portfolio/', Portfolio.as_view(), name='portfolio_page'),
    path('index/', Index.as_view(), name='index_page'),
    path('consultas/', include('app_proyecto.urls'))

]


proyectoFinal/app_proyecto/models.py
from django.db import models

# Create your models here.

class Consulta(models.Model):
    class Meta:
        db_table = "lista_consultas"

    codigo=models.AutoField(primary_key=True)
    nombre=models.CharField(max_length=50)
    email=models.CharField(max_length=50)
    descripcion=models.CharField(max_length=250)

    def __str__(self):
        return f"Nombre: {self.nombre}, Email: {self.email}"
    
    def obtener_campos(self):
        return [
            (field.verbose_name, field.value_from_object(self))
            for field in self.__class__._meta.fields[1:]
        ]



proyectoFinal/app_proyecto/views.py
from django.shortcuts import render
from .models import Consulta
from django.views import View
from django.urls import reverse_lazy

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView


# Create your views here.

class ConsultasBaseView(View):
    template_name = 'consultas.html'
    model = Consulta
    fields = '__all__'
    success_url = reverse_lazy('consultas:all')


class ConsultasListView(ConsultasBaseView, ListView):
    ...

class ConsultasDetailView(ConsultasBaseView, DetailView):
    template_name = 'consulta_detail.html'

class ConsultasCreateView(ConsultasBaseView, CreateView):
    template_name = 'consulta_create.html'
    extra_context = {
        'tipo': 'Crear Consulta'
    }

class ConsultasUpdateView(ConsultasBaseView, UpdateView):
    template_name = 'consulta_create.html'
    extra_context = {
        'tipo': 'Modificar Consulta'
    }

class ConsultasDeleteView(ConsultasBaseView, DeleteView):
    template_name = 'consulta_delete.html'
    extra_context = {
        'tipo': 'Eliminar Consulta'
    }

proyectoFinal/proyectoFinal/views.py
from django.views.generic import TemplateView

class LandingPage(TemplateView):
    template_name = "landing.html"

class Index(TemplateView):
    template_name = "pages/index.html"

class Empresa(TemplateView):
    template_name = "pages/empresa.html"

class Portfolio(TemplateView):
    template_name = "pages/portfolio.html"

class Contacto(TemplateView):
    template_name = "pages/contacto.html"

proyectoFinal/app_proyecto/templates/consulta_create.html
{% extends 'landing.html' %}
{% load static %}

{% block header %} 

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

{% endblock %}

{% block content %}

<main>
    <div class="container py-4">
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6">
                <h2 style="color: #6B33FF">Escriba su consulta:</h2>
                <div class="card-body">
                    <form method="POST"> {% csrf_token %}
                        <!-- <div class="form-group py-2">
                            <input type="text" id="txtcodigo" name="txtcodigo" class="form-control" placeholder="Código" required>
                        </div>
                        <div class="form-group py-2">
                            <input type="text" id="txtnombre" name="txtnombre" class="form-control" placeholder="Nombre" required>
                        </div>
                        <div class="form-group py-2">
                            <input type="email" name="email" id="email" class="form-control" placeholder="Email" required>
                        </div>
                        <div class="form-group py-2">
                            <input type="text" id="txtdescripcion" name="txtdescripcion" class="form-control" placeholder="realiza la consulta" required>
                        </div> -->
                        <div>{{form.as_p}}</div>
                        
                        <div class="form-group">
                            <input type="submit" value="{{ tipo }}" />
                            <a href="{% url 'consultas:all' %}" style="text-decoration: none; color: #6B33FF;">Volver atras</a>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-3"></div>
        </div>

    </div>

</main>

{% endblock %} 

proyectoFinal/app_proyecto/templates/consulta_delete.html
{% extends 'landing.html' %}
{% load static %}

{% block header %} 

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

{% endblock %}

{% block content %}

<main>
    <div class="container py-4">
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6">
                <h3 style="color: #6B33FF">¿Esta seguro de eliminar esta consulta?</h3>
                <h3>{{consulta.nombre}}</h3>
                <div class="card-body">
                    <form method="POST"> 
                        {% csrf_token %}
                        <div>{{form.as_p}}</div>
                        <div class="form-group">
                            <input type="submit" value="{{ tipo }}" />
                            <a href="{% url 'consultas:all' %}" style="text-decoration: none; color: #6B33FF;">Volver atras</a>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-3"></div>
        </div>

    </div>

</main>

{% endblock %} 

proyectoFinal/app_proyecto/templates/consultas.html
{% extends 'landing.html' %}
{% load static %}

{% block header %} 

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

{% endblock %}

{% block content %}
<main>
    <div class="container py-4">
        <div class="row">
            <div class="col">
                <div class="table-responsive py-2">
                    <h2 style="color: #6B33FF">Consultas:</h2>
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Código</th>
                                <th>Nombre</th>
                                <th>E-mail</th>
                                <th>Descripción</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for c in consultas_list %}
                            <tr>
                                <td>{{c.codigo}}</td>
                                <td>{{c.nombre}}</td>
                                <td>{{c.email}}</td>
                                <td>{{c.descripcion}}</td>
                                <td> <a href="{% url 'consultas:update' c.codigo %}">Modificar</a> | <a href="{% url 'consultas:delete' c.codigo %}">Eliminar</a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <div>
                        <a href="{% url 'consultas:create' %}">CREAR CONSULTA</a>
                    </div>
                </div>

            </div>
        </div>
    </div>
</main>

{% endblock %} 

proyectoFinal/templates/landing.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="theme-color" content="#2091F9">
    <!-- CSS -->
    {% block header %} {% endblock %}
    <link rel="stylesheet" href="{% static './css/estilos.css' %}">
    <link rel="stylesheet" href="{% static './css/normalize.css' %}">
    <link rel="stylesheet" href="{% static './css/styleIndex.css' %}">
    <link rel="shortcut icon" href="{% static './imgs/flor.png' %}">

    
    <title>NÚCLEO DÍGITAL</title>
</head>
<body>
    <header class="hero">
        <nav class="nav">
            <div class="nav__logo">
                <img src="{% static './imgs/florLogo.png' %}" class="nav__logo-img" alt="Logo-ND">
            </div>

            <ul class="nav__link nav__link--menu">
                <li class="nav__items">
                    <a href="{% url 'index_page' %}" class="nav__links">HOME</a>
                </li>
                <li class="nav__items">
                    <a href="{% url 'empresa_page' %}" class="nav__links">LA EMPRESA</a>
                </li>
                <li class="nav__items">
                    <a href="{% url 'portfolio_page' %}" class="nav__links">PORTFOLIO</a>
                </li>
                <li class="nav__items">
                    <a href="{% url 'contacto_page' %}" class="nav__links">CONTACTO</a>
                </li>
                <li class="nav__items">
                    <a href="{% url 'consultas:all' %}" class="nav__links">CONSULTAS</a>
                </li>
                <img src="{% static './imgs/close.svg' %}" class="nav__close" alt="salir">
            </ul>
            
            <div class="nav__menu">
                <img src="{% static './imgs/menu.svg' %}" class="nav__img" alt="menu">
            </div>
        </nav>
        <section class="hero__container container">
            <h1 class="hero__title">NÚCLEO DIGITAL</h1>
            <p class="hero__paragraph">Acompañamos en la evolución dígital de las empresas y organizaciones.</p>       
            {% block head %} {% endblock %} 
        </section>
    </header>
    
    <main>
        {% block content %} {% endblock %} 
    </main>

    <footer class="footer">
        <section class="footer__copy container">
            <div class="footer__social">
                <a href="#" class="footer__icons"><img src="{% static './imgs/facebook.svg' %}" alt="logoFacebook" class="footer__img"></a>
                <a href="#" class="footer__icons"><img src="{% static './imgs/twitter.svg' %}" alt="logoTwitter" class="footer__img"></a>
                <a href="#" class="footer__icons"><img src="{% static './imgs/youtube.svg' %}" alt="logoYoutube" class="footer__img"></a>
                <a href="#" class="footer__icons"><img src="{% static './imgs/instagram.svg' %}" alt="logoInstagram" class="footer__img"></a>
            </div>

            <h3 class="footer__copyright">Derechos reservados &copy; NÚCLEO DIGITAL</h3>
        </section>
    </footer>
    <script src="{% static './js/menu.js' %}"></script>
    <script src="{% static './js/bienvenida.js' %}"></script>
    <script src="{% static './js/lightbox.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

proyectoFinal/templates/pages/contacto.html
{% extends 'landing.html' %}
{% load static %}
{% block content %}
    <form action="https://formspree.io/f/xqkoogrj" method="POST" id="formulario">
        <div class="form">
            <h2>Contacto</h2>

            <div class="formulario">
                <label for="n">Nombre:</label>
                <input type="text" name="nombre" id="n" placeholder="Nombre" required> 
                <p></p>
            </div>

            <div class="formulario">
                <label for="a">Apellido:</label>
                <input type="text" name="apellido" id="a" placeholder="Apellido" required> 
                <p></p>
            </div>

            <div class="formulario">
                <label for="t">Teléfono:</label>
                <input type="tel" name="telefono" id="t" placeholder="Teléfono"> 
                <p></p>
            </div>

            <div class="formulario">
                <label for="m">E-Mail:</label>
                <input type="email" name="mail" id="m" placeholder="E-Mail" required> 
                <p></p>
            </div>

            <div class="formulario">
                <label for="c">Consulta:</label>
                <textarea name="comentario" id="c" placeholder="Escriba su consulta" required></textarea> 
                <p></p>
            </div>
            <div class="boton">
                <button type="submit" class="btn" value="Enviar"> Enviar </button>
                <button type="reset" class="btn" value="Restablecer"> Restablecer </button>
            </div>

        </div>
    </form>
    <br>
    <br>

    <link rel="stylesheet" href="{% static './css/contacto.css' %}">
    <script src="{% static './js/formulario.js' %}"></script>
    {% endblock %} 

proyectoFinal/templates/pages/empresa.html
{% extends 'landing.html' %}
{% load static %}
{% block content %}
    <main>
        <section class="container services" id="verMas">
            <h2 class="subtitle">Servicios</h2>
            <p class="services__paragraph">Nos especializamos en E-commerce, Marketing Dígital y Branding.</p>

            <div class="services__main">
                <article class="services__icons">
                    <img src="{% static './imgs/store.svg' %}" class="services__icon" alt="E-commerce">
                    <h3 class="services__title">E-commerce</h3>
                    <p class="services__paragraph">Desarrollo y Optimización de webs para venta online. Vende por internet en tu propia tienda nube.</p>
                </article>

                <article class="services__icons">
                    <img src="{% static './imgs/branding.svg' %}" class="services__icon" alt="MarketingDigital">
                    <h3 class="services__title">Marketing Digital</h3>
                    <p class="services__paragraph">Apuntamos a optimizar tu inversión publicitaria y a maximizar las ventas de tu tienda online</p>
                </article>
                
                <article class="services__icons">
                    <img src="{% static './imgs/brand.svg' %}" class="services__icon" alt="Branding">
                    <h3 class="services__title">Branding</h3>
                    <p class="services__paragraph">Identidad de marca y desarrollo de imagen institucional. Adapatamos tus necesidades técnologicas en experiencias valiosas.</p>
                </article>
            </div>
        </section>

        <section class="testimony">
            <div class="testimony__container container">
                <img src="{% static './imgs/leftarrow.svg' %}" class="testimony__arrow" id="before" alt="flecha">
                <section class="testimony__body testimony__body--show" data-id="1">
                    <div class="testimony__text">
                        <h2 class="subtitle">Agustin Fernandez, <span class="testimony__course">CEO CRZ CONSTRUCCIONES.</span></h2>
                        <p class="testimony__review">Entendieron bien nuestras metas en cuanto a la nueva imagen y gracias a ello las llevamos a cabo de una manera agil y concreta. Sin dudas son el socio ideal para compañias que buscan expertos en diseño y desarrollo web</p>
                    </div>

                    <figure class="testimony__picture">
                        <img src="{% static './imgs/foto.jpg' %}" class="testimony__img" alt="FotoJordan">
                    </figure>
                </section>

                <section class="testimony__body" data-id="2">
                    <div class="testimony__text">
                        <h2 class="subtitle">Martina Varela, <span class="testimony__course">HOME DECORACIONES.</span></h2>
                        <p class="testimony__review">No tenemos más que palabras de agradecimiento para todo el equipo. En un periodo muy corto de tiempo aumentaron nuestras ventas de manera sustancial. Nuestra nueva tienda online es lo más.</p>
                    </div>

                    <figure class="testimony__picture">
                        <img src="{% static './imgs/foto1.jpg' %}" class="testimony__img" alt="FotoAle">
                    </figure>
                </section>

                <section class="testimony__body" data-id="3">
                    <div class="testimony__text">
                        <h2 class="subtitle">Paula Sophia Abella, <span class="testimony__course">MAGNOLIA MODA.</span></h2>
                        <p class="testimony__review">Se adaptaron a la realidad de mi marca y armaron un plan integral de trabajo. Durante el proceso me enseñaron, me ayudaron, se brindarón al 100%. ¡Muchas gracias por todo! </p>
                    </div>

                    <figure class="testimony__picture">
                        <img src="{% static './imgs/foto2.jpg' %}" class="testimony__img" alt="FotoKaren">
                    </figure>
                </section>

                <img src="{% static './imgs/rightarrow.svg' %}" class="testimony__arrow" id="next" alt="flecha">
            </div>

        </section>

        <section class="questions container">
            <h2 class="subtitle">Preguntas Frecuentes</h2>
            <p class="questions__paragraph">Respondemos todas las dudas y/o consultas</p>

            <section class="questions__container">
                <article class="questions__padding">
                    <div class="questions__answer">
                        <h3 class="questions__title">¿Como puedo contratar sus servicios?
                            <span class="questions__arrow">
                                <img src="{% static './imgs/arrow.svg' %}" class="questions_img" alt="arrow">
                            </span>
                        </h3>

                        <p class="questions__show">En nuestra sección de Contacto que encuentras en el Menu Principal, o por cualquiera de nuestras Redes Sociales</p>
                    </div>
                </article>

                <article class="questions__padding">
                    <div class="questions__answer">
                        <h3 class="questions__title">¿Pregunta 2?
                            <span class="questions__arrow">
                                <img src="{% static './imgs/arrow.svg' %}" class="questions_img" alt="arrow">
                            </span>
                        </h3>

                        <p class="questions__show"> Respuesta a la Pregunta 2 en este espacio</p>
                    </div>
                </article>

                <article class="questions__padding">
                    <div class="questions__answer">
                        <h3 class="questions__title">¿Pregunta 3?
                            <span class="questions__arrow">
                                <img src="{% static './imgs/arrow.svg' %}" class="questions_img" alt="arrow">
                            </span>
                        </h3>

                        <p class="questions__show"> Respuesta a la Pregunta 3 en este espacio</p>
                    </div>
                </article>
            </section>

            <section class="questions__offer">
                <h2 class="subtitle">Estamos a la vanguardia de la tecnologia</h2>
                <p class="questions__copy">En Núcleo Digital nos comprometemos con cada uno de nuestros clientes y cumplimos con entregas en tiempo y forma.</p>
            </section>
        </section>
    </main>
    <script src="{% static './js/slider.js' %}"></script>
    <script src="{% static '/js/questions.js' %}"></script>
{% endblock %} 

proyectoFinal/templates/pages/index.html
{% extends 'landing.html' %}
{% load static %}

{% block head %}
<section class="hero__container container">
    <div class="container2">
        <p id="demo"></p>
        <br>
        <label for="name" >Ingresa tu nombre</label>
        <input type="text" id="nombre" required>
        <button class="cta" onclick="bienvenida()">Enviar</button>
    </div>
</section>
{% endblock %} 
{% block content %}
<main> 
    <section class="texto">
        <p>Te invitamos a recorrer nuestra página web, donde encontrarás algunos ejemplos de nuestros trabajos, donde le ponemos nuestra pasión y compromiso con los clientes.</p>
        <br>
        <p>Nuestra web está pensada para que encuentres de forma sencilla y atractiva toda la información que necesites sobre nuestra empresa y nuestros productos.</p>
        <br>    
        <p>Queremos que nos conozcas, que puedas saber de dónde venimos y presentarte a nuestro equipo, que puedas informarte con detalle de cómo cuidamos nuestros clientes. Te contamos nuestra manera de trabajar y nuestro compromiso con el entorno. Esperamos que nos cuentes si te ha gustado o si tienes sugerencias para hacernos mejorar.
            
            Muchas gracias tu visita.</p>
        </section>
        <section class="gallery" id="galeria">
            <div class="contenedor">
            <div class="contenedor-galeria">
                <img src="{% static './imgs/ejemplo1.jpg' %}" alt="" class="img_galeria">
                <img src="{% static '/imgs/ejemplo2.jpg' %}" alt="" class="img_galeria">
                <img src="{% static '/imgs/ejemplo3.jpg' %}" alt="" class="img_galeria">
            </div>
        </div>
    </section>
    <section class="imagen-light">
        <img src="{% static '/imgs/close.svg' %}" alt="" class="close">
        <img src="" alt="" class="agregar-imagen">
    </section>
    <section>
        <div>
            <br>
            <img src="{% static './imgs/flor1.png' %}" alt="" id="flor">
        </div>
    </section>
</main>
{% endblock %} 

proyectoFinal/templates/pages/portfolio.html
{% extends 'landing.html' %}
{% load static %}
{% block content %}
    <main>
        <section>
            <h2 class="subtitle" style="text-align: center;">PROYECTOS REALIZADOS</h2>
            <div id="contenido">

            </div>
        </section>
    </main>
    <script src="{% static './js/fetchApi.js' %}"></script>
{% endblock %} 